---
# tasks file for system_profile in linux
- name: adding ssh session timeout in linux
  blockinfile:
    path: "{{tmoutpath}}"
    insertafter: EOF
    backup: yes
    state: present
    block: |
      export "#This is a test block added by Ansible……N01506010"
      export TMOUT=1800
